version: '3.8'

services:
  # Vue Frontend (Served by Nginx)
  infrafrontend:
    image: ${FRONTEND_IMAGE:-vasanthkumar03/infraops-frontend:latest}
    container_name: infraops-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
